# Generated by Django 3.1.7 on 2021-04-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadii', '0002_order_orderitem_product_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_fan',
        ),
    ]
